//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio2.AlumWSDL {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://ehusw.es/jav/ServiciosWeb/comprobarmatricula.php?wsdl", ConfigurationName="AlumWSDL.MatriculasPortType")]
    public interface MatriculasPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ehusw.es/jav/ServiciosWeb/comprobarmatricula.php/comprobar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="z")]
        string comprobar(string x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ehusw.es/jav/ServiciosWeb/comprobarmatricula.php/comprobar", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="z")]
        System.Threading.Tasks.Task<string> comprobarAsync(string x);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MatriculasPortTypeChannel : Laboratorio2.AlumWSDL.MatriculasPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatriculasPortTypeClient : System.ServiceModel.ClientBase<Laboratorio2.AlumWSDL.MatriculasPortType>, Laboratorio2.AlumWSDL.MatriculasPortType {
        
        public MatriculasPortTypeClient() {
        }
        
        public MatriculasPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatriculasPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatriculasPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatriculasPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string comprobar(string x) {
            return base.Channel.comprobar(x);
        }
        
        public System.Threading.Tasks.Task<string> comprobarAsync(string x) {
            return base.Channel.comprobarAsync(x);
        }
    }
}
